import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {handleRequest} from './server.mjs';
const els={},document={getElementById:id=>els[id]??={value:({width:'80',step:'3',surfaceMax:'5',surfaceWeight:'0.8'})[id]||'',checked:id==='surfaceDemo',removeAttribute(){},setAttribute(){},options:[]},querySelectorAll:()=>[]};
const source=fs.readFileSync('network.js','utf8')+'\n'+fs.readFileSync('surface.js','utf8')+'\n'+fs.readFileSync('app.js','utf8').split("$('resetWalkingRoute').onclick")[0];
const window={JANGDAE_DATA:JSON.parse(fs.readFileSync('jangdae-data.json','utf8'))};vm.runInNewContext(fs.readFileSync('area-network.js','utf8')+'\n'+source+`
render=()=>{};data=initialWalkingData();assert(data.isAreaOverview);assert.equal(data.segments.length,1807);assert(data.segments.every(s=>s.surfaceGrade>=1&&s.surfaceGrade<=5));
data=routeData({route:{properties:{totalDistance:100,totalTime:120},legs:[{steps:[{properties:{guidance:'대로'},path:{points:[[127.338,36.365],[127.339,36.365]]}}]}]}},{lat:36.365,lng:127.338},{lat:36.365,lng:127.339});assert(!data.isAreaOverview);surfaceCandidates=[{id:'old'}];chosenSurfaceId='old';pointClickStage=2;customPoints={'picked-from':{lat:36.365,lng:127.338}};routeActive=true;beginTwoPointSelection();assert.equal(surfaceCandidates.length,0);assert.equal(chosenSurfaceId,null);assert.equal(pointClickStage,0);assert.equal(routeActive,false);assert(data.isAreaOverview);assert.equal(data.segments.length,1807);assert.equal(Object.keys(customPoints).length,0);assert.equal($('from').value,'');assert.equal($('to').value,'');resetWalkingSelection();assert.equal(data.segments.length,1807);
`,{window,document,structuredClone,assert,Map,Set,Date,console});
const origin='https://lightemittingdiode.github.io',url='https://backend.test/api/walking-candidates';const preflight=await handleRequest(new Request(url,{method:'OPTIONS',headers:{Origin:origin}}),{},{});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),origin);
const response=await handleRequest(new Request(url,{method:'POST',headers:{Origin:origin},body:'{}'}),{},{});assert.equal(response.status,503);assert.equal(response.headers.get('Access-Control-Allow-Origin'),origin);
assert.equal((await handleRequest(new Request(url,{method:'OPTIONS',headers:{Origin:'https://other.test'}}),{},{})).status,403);
console.log('Verified 1,807 graded initial/reset sections, immediate reselect clearing, no route metrics/pins after clearing, and Pages-only CORS preflight/error handling.');

