'use strict';
const VIEW_CENTER={lat:36.365473,lng:127.338021},VIEW_RADIUS_M=1000;
let pointClickStage=0,surfaceCandidates=[],surfaceOverrides=new Map(),chosenSurfaceId=null,surfaceFailedCount=0,surfaceRejectedCount=0,lastPointInput=null,demoMainCorridors=[],routeSelectionPending=null;
const routeModes=[{value:'0',label:'최단 거리',description:'거리 우선'},{value:'0.8',label:'최적 거리',description:'안전 + 최단 절충'},{value:'2',label:'안전 거리',description:'위험도 우선'}];
const surfaceLabels={1:'매우 양호',2:'양호',3:'거친 노면',4:'매우 거침',5:'통행 곤란'};
function demoSurfaceKey(p){const c=demo.center;return Math.floor((p.lng-c.lng)*111195*Math.cos(c.lat*Math.PI/180)/25)+':'+Math.floor((p.lat-c.lat)*111195/25);}
function demoRoadClass(segment){const name=segment.name||'';if(segment.category==='main')return 'main';if(segment.category==='alley')return 'alley';if(/횡단보도|횡단|계단/.test(name))return 'crossing';if(/대로/.test(name))return 'main';if(/골목|소로|(?:로|길)\s*\d+(?:번)?길/.test(name))return 'alley';if(segment.category==='local'||/\([^)]*(?:로|길)\)/.test(name))return 'local';const p=segment.path[0],q=segment.path.at(-1),mid={lat:(p.lat+q.lat)/2,lng:(p.lng+q.lng)/2},scale=111195*Math.cos(mid.lat*Math.PI/180),sx=(q.lng-p.lng)*scale,sy=(q.lat-p.lat)*111195,sl=Math.hypot(sx,sy);for(const edge of demoMainCorridors){const a=edge.path[0],b=edge.path.at(-1),dx=(b.lng-a.lng)*scale,dy=(b.lat-a.lat)*111195,len=Math.hypot(dx,dy);if(!len||!sl||Math.abs((sx*dx+sy*dy)/(sl*len))<.7)continue;const px=(mid.lng-a.lng)*scale,py=(mid.lat-a.lat)*111195,t=Math.max(0,Math.min(1,(px*dx+py*dy)/(len*len)));if(Math.hypot(px-t*dx,py-t*dy)<=18)return 'main';}return 'mixed';}
const demoRoadLabels={main:'대로변',alley:'골목',local:'이면도로',crossing:'횡단·계단 구간',mixed:'도로 유형 미확인'};
function demoSurfaceGrade(p,roadClass='mixed'){const key=demoSurfaceKey(p);if(surfaceOverrides.has(key))return surfaceOverrides.get(key);let hash=2166136261;for(const ch of key)hash=Math.imul(hash^ch.charCodeAt(0),16777619);const n=(hash>>>0)%10;if(roadClass==='main')return n<4?1:n<7?2:n<9?3:4;if(roadClass==='alley'||roadClass==='local')return n<1?1:n<3?2:n<6?3:n<9?4:5;if(roadClass==='crossing')return n<5?2:3;return n<4?1:n<7?2:n<9?3:4;}
function subdivideWalkingData(dataset){const nodes=[...dataset.nodes],segments=[];for(const old of dataset.segments){const a=old.path[0],b=old.path.at(-1),count=Math.max(1,Math.ceil(distance(old)/15));for(let i=0;i<count;i++){const p={lat:a.lat+(b.lat-a.lat)*i/count,lng:a.lng+(b.lng-a.lng)*i/count},q={lat:a.lat+(b.lat-a.lat)*(i+1)/count,lng:a.lng+(b.lng-a.lng)*(i+1)/count},id=old.id+'-'+i,from=id+'a',to=id+'b';nodes.push({id:from,name:old.name+' 시작',...p},{id:to,name:old.name+' 끝',...q});segments.push({...old,id,from,to,path:[p,q],apiTimeSeconds:(old.apiTimeSeconds??0)/count});}}return {...dataset,nodes,segments};}
function gradeSegments(dataset){const useDemo=$('surfaceDemo').checked;for(const s of dataset.segments){const p={lat:(s.path[0].lat+s.path[1].lat)/2,lng:(s.path[0].lng+s.path[1].lng)/2};s.surfaceKey=demoSurfaceKey(p);s.gradeIsDemo=false;
 if(s.modelMatched){s.surfaceGrade=Number.isInteger(s.surfaceGrade)?s.surfaceGrade:null;s.demoRoadClass=null;s.riskIsDemo=false;s.roadTypeLabel='카카오 도보 경로 · 모델 관측';continue;}
 if(!useDemo){s.surfaceGrade=null;s.demoRoadClass=null;s.riskIsDemo=false;s.roadTypeLabel='카카오 도보 경로';continue;}
 const roadClass=demoRoadClass(s),grade=demoSurfaceGrade(p,roadClass);s.demoRoadClass=roadClass;s.roadTypeLabel='카카오 도보 · '+demoRoadLabels[roadClass]+' (시연 분류)';s.surfaceGrade=grade;s.gradeIsDemo=true;s.riskIsDemo=true;s.surface=grade+'등급 · '+surfaceLabels[grade]+' (시연)';s.staticRisk=[0,10,24,48,76,96][grade];const movement=Math.abs(Math.round(p.lat*100000)+Math.round(p.lng*100000))%4;s.dynamicRisk=roadClass==='main'?movement*4:roadClass==='alley'||roadClass==='local'?18+movement*6:movement*12;s.widthCm=grade===5?65:110;s.stepCm=grade===5?8:grade===4?2:0;s.passability=grade===5?'blocked':grade>=3?'caution':'pass';s.obstacle='시연 상황';s.confidence=0;s.evidence='대로변은 낮은 위험, 골목·이면도로는 높은 위험을 더 많이 배치한 시연 값입니다. '+demoRoadLabels[roadClass]+' 유형은 경로 안내와 위치로 시연 분류했으며 현장 측정값이 아닙니다.';
 }}
function evaluateSurfaceCandidate(candidate){const before=data;data=candidate.dataset;try{matchWalkingObservations();gradeSegments(data)}finally{data=before}const segments=candidate.dataset.segments,max=Number($('surfaceMax').value||5);let length=0,gradeSum=0,blocked=0,unknown=0,worst=0,riskSum=0,riskLength=0,maxRisk=0,riskUnknown=0;
 for(const s of segments){const len=distance(s);length+=len;if(!s.surfaceGrade||status(s)==='unknown'){unknown++;}else{worst=Math.max(worst,s.surfaceGrade);gradeSum+=s.surfaceGrade*len;if(s.surfaceGrade>max||status(s)==='blocked')blocked++;}if(Number.isFinite(s.staticRisk)&&Number.isFinite(s.dynamicRisk)){const risk=Math.max(s.staticRisk,s.dynamicRisk);riskSum+=risk*len;riskLength+=len;maxRisk=Math.max(maxRisk,risk);}else riskUnknown++;}
 const meters=candidate.dataset.walkingSummary.totalDistance;candidate.metrics={distanceM:meters,timeSeconds:candidate.dataset.walkingSummary.totalTime,averageGrade:length?gradeSum/length:0,worstGrade:worst,averageRisk:riskUnknown||!riskLength?null:riskSum/riskLength,maxRisk:riskUnknown||!riskLength?null:maxRisk,riskUnknown,blocked,unknown,allowed:blocked===0&&unknown===0&&riskUnknown===0,score:meters+(riskLength?riskSum/riskLength:100)/100*meters*2};return candidate;}
function routeSignature(route){const points=[];for(const leg of route.legs||[])for(const step of leg.steps||[])for(const p of step.path?.points||[]){const key=p.map(n=>n.toFixed(6)).join(',');if(points.at(-1)!==key)points.push(key)}return points.join(';');}
function walkingGeometryQuality(dataset){const scale=111195*Math.cos(dataset.center.lat*Math.PI/180),origin=dataset.center,xy=p=>({x:(p.lng-origin.lng)*scale,y:(p.lat-origin.lat)*111195}),edges=[],vertices=[];let traveled=0,repeatedM=0,loop=false;
 for(const s of dataset.segments){const p=xy(s.path[0]),q=xy(s.path.at(-1)),dx=q.x-p.x,dy=q.y-p.y,len=Math.hypot(dx,dy);if(len<.1)continue;let overlap=0;
 for(const old of edges){const crossP=Math.abs(dx*(old.p.y-p.y)-dy*(old.p.x-p.x))/len,crossQ=Math.abs(dx*(old.q.y-p.y)-dy*(old.q.x-p.x))/len;if(crossP>1||crossQ>1)continue;const t1=((old.p.x-p.x)*dx+(old.p.y-p.y)*dy)/len,t2=((old.q.x-p.x)*dx+(old.q.y-p.y)*dy)/len;overlap=Math.max(overlap,Math.max(0,Math.min(len,Math.max(t1,t2))-Math.max(0,Math.min(t1,t2))));}
 repeatedM+=overlap;for(const v of vertices)if(traveled-v.at>25&&Math.hypot(p.x-v.x,p.y-v.y)<1)loop=true;vertices.push({...p,at:traveled});edges.push({p,q});traveled+=len;}
 if(edges.length){const q=edges.at(-1).q;for(const v of vertices)if(traveled-v.at>25&&Math.hypot(q.x-v.x,q.y-v.y)<1)loop=true;}
 return {repeatedM,loop,rejected:loop||repeatedM>=10};}
function makeSurfaceCandidates(payload,a,b){const all=[...payload.candidates,...(payload.networkRoutes||[])];demoMainCorridors=all.flatMap(c=>routeData({route:c.route},a,b).segments.filter(s=>/대로/.test(s.name)&&!/횡단보도|횡단|계단/.test(s.name)));networkInputs=[];networkFallback=[];surfaceRejectedCount=0;const seen=new Set();for(const c of all){const key=routeSignature(c.route);if(seen.has(key))continue;seen.add(key);const dataset=routeData({route:c.route},a,b),quality=walkingGeometryQuality(dataset),candidate={id:c.id,label:c.label,quality,dataset:subdivideWalkingData(dataset)};networkInputs.push(candidate);if(!c.networkOnly&&!quality.rejected)networkFallback.push(candidate);else if(!c.networkOnly)surfaceRejectedCount++;}return solveSurfaceNetwork();}
function chooseSurfaceCandidate(id){const candidate=surfaceCandidates.find(c=>c.id===id);if(!candidate)return;chosenSurfaceId=id;data=candidate.dataset;selected=data.segments[0]?.id;route=[];routeGeometry=[];roadFilter='all';$('roadFilter').value='all';populate();render();showSurfaceSummary();}
function bestSurfaceCandidate(mode=$('surfaceWeight').value){const graphChoice=surfaceCandidates.find(c=>c.graphModes?.includes(mode));if(graphChoice)return graphChoice;let pool=surfaceCandidates;const valid=pool.filter(c=>c.metrics.allowed);if(mode==='2'&&valid.length){const shortest=Math.min(...valid.map(c=>c.metrics.distanceM)),limit=Math.max(shortest*1.5,shortest+80);pool=valid.filter(c=>c.metrics.distanceM<=limit);}return [...pool].sort((a,b)=>{const x=a.metrics,y=b.metrics,valid=Number(y.allowed)-Number(x.allowed)||x.blocked-y.blocked||x.unknown-y.unknown||x.riskUnknown-y.riskUnknown;if(valid)return valid;if(mode==='0')return x.distanceM-y.distanceM;if(mode==='2')return (x.averageRisk??100)-(y.averageRisk??100)||(x.maxRisk??100)-(y.maxRisk??100)||x.distanceM-y.distanceM;return x.score-y.score||x.distanceM-y.distanceM;})[0];}
function renderRoutingOverview(){const panel=$('routingOverview');if(!panel)return;panel.hidden=!data.isKakao;const mode=$('surfaceWeight').value||'0.8',selected=surfaceCandidates.find(c=>c.id===chosenSurfaceId),m=selected?.metrics,fmtRisk=n=>n===null||n===undefined?'미확인':n.toFixed(1);$('routingModeTabs').innerHTML=routeModes.map(option=>'<button type="button" data-route-mode="'+option.value+'" class="route-mode '+(option.value===mode?'active':'')+'" aria-pressed="'+(option.value===mode)+'"><b>'+option.label+'</b><small>'+option.description+'</small></button>').join('');document.querySelectorAll('[data-route-mode]').forEach(el=>el.onclick=()=>{$('surfaceWeight').value=el.dataset.routeMode;updateSurfaceRoutes();});$('routingMetrics').innerHTML=[['이동거리',m?Math.round(m.distanceM).toLocaleString():'—',m?'m':''],['예상 시간',m?Math.max(1,Math.ceil(m.timeSeconds/60)):'—',m?'분':''],['평균 위험도',m?fmtRisk(m.averageRisk):'—',m&&m.averageRisk!==null?'/100':''],['최대 위험도',m?fmtRisk(m.maxRisk):'—',m&&m.maxRisk!==null?'/100':'']].map(([label,value,unit])=>'<div><span>'+label+'</span><strong>'+value+'<small>'+unit+'</small></strong></div>').join('');$('routingSummaryNote').textContent=m?(m.allowed?'조건 충족 · ':'조건 미충족 · ')+(surfaceCandidates.some(c=>c.graphModes)?surfaceCandidates.length===1?'대체 경로 없음 · 세 옵션이 같습니다 · ':surfaceCandidates.length+'개 서로 다른 경로 · ':surfaceCandidates.length+'개 카카오 후보 비교 · ')+(data.segments.some(s=>s.gradeIsDemo)?'위험도 시연 값':'실측 모델 관측'):data.isAreaOverview?'전체 샘플 구간 상태 · '+data.segments.length.toLocaleString()+'개 구간 · 두 점을 지정하면 길찾기':'출발지와 도착지를 지정하면 결과가 표시됩니다.';}
function updateSurfaceRoutes(){if(networkInputs.length)surfaceCandidates=solveSurfaceNetwork();else if(data.isAreaOverview){const before=data;data=initialWalkingData();render();return;}else for(const candidate of surfaceCandidates)evaluateSurfaceCandidate(candidate);const best=bestSurfaceCandidate();if(best)chooseSurfaceCandidate(best.id);else render();}
function renderSurfaceControls(){if(!$('surfaceRoutes'))return;$('surfaceSettings').hidden=!data.isKakao;$('surfaceRoutes').hidden=true;$('surfaceRoutes').innerHTML='';renderRoutingOverview();$('pointPickHint').textContent=pointClickStage===0?'첫 번째 점을 찍어 출발지를 지정하세요.':pointClickStage===1?'두 번째 점을 찍으면 노면 등급을 반영해 길찾기합니다.':'경로를 누르면 해당 구간의 정보를 확인할 수 있습니다.';$('mapPickHint').textContent=$('pointPickHint').textContent;}
function showSurfaceSummary(){const candidate=surfaceCandidates.find(c=>c.id===chosenSurfaceId);if(!candidate)return;const m=candidate.metrics,s=data.walkingSummary,sim=data.segments.some(s=>s.gradeIsDemo);$('routeResult').textContent=(m.allowed?'노면 조건을 반영한 선택 경로':'조건을 충족하는 선택 경로가 아닙니다')+' · '+Math.round(m.distanceM)+' m · 약 '+Math.ceil(s.totalTime/60)+'분 · 평균 위험도 '+(m.averageRisk===null?'미확인':m.averageRisk.toFixed(1)+'/100')+' · 최대 위험도 '+(m.maxRisk===null?'미확인':m.maxRisk.toFixed(1)+'/100')+'. '+(data.graphDerived?'카카오 도보 연결 구간에서 거리와 위험도를 각각 계산했습니다. 예상 시간은 구간별 카카오 시간을 합산합니다.':surfaceCandidates.length+'개 카카오 도보 후보를 비교했습니다.')+(m.blocked?' 허용 노면 등급·폭·단차를 벗어난 '+m.blocked+'개 구간이 있습니다.':'')+(m.unknown?' '+m.unknown+'개 구간의 노면 관측이 없어 통행을 판단할 수 없습니다.':'')+(sim?' 노면·위험도는 시연 값입니다.':' 실측 모델 관측을 사용합니다.')+(surfaceRejectedCount?' 반복·왕복 이동 후보 '+surfaceRejectedCount+'개를 제외했습니다.':'')+(surfaceFailedCount?' 일부 후보 조회에 실패했습니다.':'');}
async function fetchSurfaceRoutes(){const a=node($('from').value),b=node($('to').value);if(!a||!b){$('routeResult').textContent='지도에서 출발·도착 두 점을 지정하세요.';return {found:false}}const generation=++walkingGeneration;routeActive=true;$('routeBtn').disabled=true;$('routeResult').textContent='카카오 도보 후보를 조회하고 노면 등급을 비교하는 중…';surfaceCandidates=[];data.segments=[];data.walkingSummary=null;selected=null;render();
 try{const response=await fetch((window.MOVEAWHEEL_API_BASE||'')+'/api/walking-candidates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from:{lat:a.lat,lng:a.lng},to:{lat:b.lat,lng:b.lng}})}),payload=await response.json();if(generation!==walkingGeneration)return {found:false,stale:true};if(!response.ok)throw new Error(payload.error||'후보 경로를 불러오지 못했습니다.');surfaceFailedCount=payload.failedCount||0;surfaceCandidates=makeSurfaceCandidates(payload,a,b);const best=bestSurfaceCandidate();if(!best)throw new Error('반복·왕복 이동이 없는 도보 후보를 찾지 못했습니다. 출발·도착 위치를 조금 바꿔주세요.');chooseSurfaceCandidate(best.id);return {found:best.metrics.allowed,distanceM:best.metrics.distanceM,candidateCount:surfaceCandidates.length};}
 catch(error){if(generation===walkingGeneration){$('routeResult').textContent=error.message;$('routingSummaryNote').textContent=error.message;}return {found:false};}finally{if(generation===walkingGeneration)$('routeBtn').disabled=false;}}
function twoPointClick(point){if(!data.isKakao)return;if(lastPointInput&&Date.now()-lastPointInput.time<200&&Math.hypot((point.lat-lastPointInput.point.lat)*111195,(point.lng-lastPointInput.point.lng)*111195*Math.cos(point.lat*Math.PI/180))<3)return;const c=data.center;if(Math.hypot((point.lat-c.lat)*111195,(point.lng-c.lng)*111195*Math.cos(c.lat*Math.PI/180))>VIEW_RADIUS_M){$('routeResult').textContent='반경 1km 안에서 두 점을 지정하세요.';$('routingSummaryNote').textContent='반경 1km 안에서 두 점을 지정하세요.';return}if(pointClickStage>=2)return;lastPointInput={point,time:Date.now()};if(routeSelectionPending){const end=pointClickStage===0?'from':'to';routeSelectionPending[end]={...point};pointClickStage++;if(pointClickStage===1){render();return}const points=routeSelectionPending;routeSelectionPending=null;customPoints={'picked-from':{...points.from,id:'picked-from',name:'출발'},'picked-to':{...points.to,id:'picked-to',name:'도착'}};$('from').value='picked-from';$('to').value='picked-to';pickedPoint=null;fetchSurfaceRoutes();return;}const endpoint=pointClickStage===0?'from':'to';pointClickStage++;pickedPoint={...point,segmentId:null};assignPoint(endpoint);if(pointClickStage===1){$('to').value='';render();$('routeResult').textContent='출발지를 지정했습니다. 두 번째 점을 찍어 도착지를 지정하세요.';}else fetchSurfaceRoutes();}
function resetWalkingSelection(){routeSelectionPending=null;if(!data.isKakao)chooseWalkingMode(false);pointClickStage=0;lastPointInput=null;walkingGeneration++;surfaceCandidates=[];networkInputs=[];networkFallback=[];chosenSurfaceId=null;surfaceRejectedCount=0;surfaceFailedCount=0;data=initialWalkingData();customPoints={};pickedPoint=null;selected=null;route=[];routeGeometry=[];routeActive=false;$('from').value='';$('to').value='';$('routeBtn').disabled=false;render();$('segmentPanel')?.removeAttribute('open');$('routeResult').textContent='첫 번째 점은 출발지, 두 번째 점은 도착지입니다.';}
function editDemoGrade(grade){const segment=data.segments.find(s=>s.id===selected);if(!segment||!segment.gradeIsDemo)return;surfaceOverrides.set(segment.surfaceKey,grade);updateSurfaceRoutes();}

function applyDemoRoadBias(dataset){if(!dataset.isDemo)return;for(const s of dataset.segments){const mid=s.path?{lat:(s.path[0].lat+s.path.at(-1).lat)/2,lng:(s.path[0].lng+s.path.at(-1).lng)/2}:dataset.nodes.find(n=>n.id===s.from),roadClass=s.category==='main'?'main':s.category==='alley'?'alley':s.category==='local'?'local':'mixed',grade=demoSurfaceGrade(mid,roadClass);s.surfaceGrade=grade;s.staticRisk=[0,10,24,48,76,96][grade];s.dynamicRisk=roadClass==='main'?8:roadClass==='alley'||roadClass==='local'?30:18;s.widthCm=grade===5?65:roadClass==='main'?140:95;s.stepCm=grade===5?8:grade>=4?2:0;s.passability=grade===5?'blocked':grade>=3?'caution':'pass';s.surface=grade+'등급 · '+surfaceLabels[grade]+' (시연)';s.evidence='도로 유형별 시연 배치: 대로변은 낮은 위험, 골목·이면도로는 높은 위험을 더 많이 배치합니다. 실제 위험도 관측이 아닙니다.';}}

function beginTwoPointSelection(){resetWalkingSelection();}
function displayRoutingEndpoints(){if(routeSelectionPending)return [[routeSelectionPending.from,'출발'],[routeSelectionPending.to,'도착']];return [[node($('from').value),'출발'],[node($('to').value),'도착']];}
